### ISSUE TITLE
rbx crash: invalid fastbin entry

### ISSUE THREAD

**Issue by chanks** [rubinius/rubinius#2963] opened 2014-03-02 19:39 UTC
I got a crash in rbx while running my gem's specs on Travis due to an "invalid fastbin entry". The backtrace starts at line 1050 here:

https://travis-ci.org/chanks/que/jobs/19903979#L1050

Since it crashed on Travis I don't have access to the machine, and I haven't been able to reproduce it on mine, and even on Travis the specs ran successfully 60 times before crashing on attempt 61 (we repeat the specs many times to flush out race conditions). It also appears to have happened during startup, before the specs even began running. The only C-extension we use extensively is the pg gem, but I don't see any mention of it in the backtrace.

I'm hoping that this backtrace is enough to figure out the issue, because there's not a lot else to go on. Let me know if there's anything else I can add.

Thanks!

**Comment by YorickPeterse** [comment] 2015-02-18 19:34
Does this still occur on Rubinius 2.5.2? If so, could you provide a way for us to reproduce it?

**Comment by YorickPeterse** [comment] 2015-07-30 21:59
Closing this due to lack of further feedback. Feel free to re-open if the issue still persists using the latest version of Rubinius.

**Closed by YorickPeterse** 2015-07-30 21:59 UTC
Labels: Needs feedback
