### ISSUE TITLE
NameError: wrong constant name BIG∞

### ISSUE THREAD

**Issue by fny** [rubinius/rubinius#3382] opened 2015-04-28 01:17 UTC
`BIG∞ = BigDecimal::INFINITY` is perfectly valid in Ruby 1.9.3+ but doesn't work in Rubinius. :cry:

**Comment by jemc** [comment] 2015-04-28 01:34
It's rather obnoxious that [the Symbol-validation logic for this in Rubinius is written in C++](https://github.com/rubinius/rubinius/blob/6ce75ef91493f4df1a192ea4e5429aadc04fed13/vm/symbol_table.cpp#L19-L27), when as far as I can tell it is not *really* an integral part of the VM.

If you want a quick workaround, you can do something like:
```ruby
class Symbol
  def is_constant?
    true
  end
end
```

That will allow any symbol to be used in a `const_get` or `const_set`.  Obviously, it would be better in the long run to improve the Symbol validator logic (probably starting by moving it to Ruby if possible).

**Comment by fny** [comment] 2015-04-28 01:50
Monkey patching is a no go. It seems like that alphanumeric check just needs to go and the tests needs to be updated accordingly?

**Comment by jemc** [comment] 2015-04-28 01:50
I think I've confirmed that no C++ code is depending on this logic being in C++ space, so it's safe to move to Ruby.  

We can eliminate from C++:
`SymbolTable::Kind`
`SymbolTable::kinds`
`SymbolTable::detect_kind()`
`SymbolTable::kind()`
`Rubinius.primitive+ :symbol_is_ivar (Symbol::is_ivar_p())`
`Rubinius.primitive+ :symbol_is_cvar (Symbol::is_cvar_p())`
`Rubinius.primitive+ :symbol_is_constant (Symbol::is_constant_p())`

We just need to be sure it's done in a way that isn't a performance hit.  Most obviously, it shouldn't be recalculating a Symbol's constant-ness every time this method is called, because it's not going to change.

**Comment by jemc** [comment] 2015-04-28 03:05
In terms of not incurring a performance hit by moving to Ruby - it may tougher than it sounds.

You can base the `is_constan?` and similar methods on a single method that calculates the "kind" of symbol as currently calculated in C++.  In my original implementation, I was using a method called `__kind__`.  However, storing the result of the `__kind__` calculation in an instance variable so that you don't have to repeat the calculation isn't possible because of: `can't modify frozen instance of Symbol (RuntimeError)`.

There are some other solutions that have come to my mind, but none are particularly elegant.  If anyone has any ideas for an elegant way to *Use Ruby* here, please jump in.

If we have to stay in C++, apparently this is the logic in MRI to try to match: http://rxr.whitequark.org/mri/source/parse.y?v=2.1.2#10228


For references,

**Closed** 2015-04-29 20:59 UTC
