### ISSUE TITLE
Compile failure with rvm and clang/clang++

### ISSUE THREAD

**Issue by crashtech** [rubinius/rubinius#3484] opened 2015-08-14 12:25 UTC
Log files for more information in [this gist.](https://gist.github.com/crashtech/04f217833346b97192b5).

I've tried to compile RBX using RVM but I always get the "clang: error: unknown argument: '-fstack-protector-strong'" error.

I tried with 2.5.2 and 2.4.1 versions both using llvm 3.4.2 version.

I've been searching on the Internet for a solution, and tried to Update de llvm version, but I can't compile any 3.5.x version without getting more errors, and the version 3.6.x ins't compatible.

The closest that I got was setting an "CXXFLAGS" and specifying the clang and clang++ running:
```
export CXXFLAGS="-Qunused-arguments"
rvm install rbx-head -C --cc=clang,--cxx=clang++
```

I'm using Centos7 by the way.

**Comment by YorickPeterse** [comment] 2015-08-14 12:37
The latest version of Rubinius (2.5.8) should work fine with any LLVM version <= 3.5. If it's possible to compile without involving RVM that would be great, there have been numerous cases in the past where somehow the combination of RVM and Rubinius would mess things up.

If this CentOS happens to be Amazon Linux (which is based on CentOS) you can also grab binaries from http://rubinius.olery.com/amazon/2015.03/x86_64/rubinius-2.5.8.tar.bz2.

**Comment by brixen** [comment] 2015-08-14 16:17
@crashtech can you, by chance, recommend a VBox image I can use to try to reproduce your issue?

**Comment by crashtech** [comment] 2015-08-14 22:47
You could use the CentOS 7.0 Base.
Just update the VM, download RVM exactly the way the http://rvm.io/ says, and then try to install rbx-head.

Once you have the minimum VM installed:
```
yum update -y
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | bash
source /etc/profile.d/rvm.sh
rvm install rbx-head
```

**Comment by crashtech** [comment] 2015-08-22 04:25
For those who are having the same problem, I solved this issue this way:

 - Open the file "/usr/local/rvm/src/rbx-head/rakelib/blueprint.rb" from a different console.
 - Run the installation using the clang "rvm install rbx-head -C --cc=clang,--cxx=clang++"
 - During the configuration step, go aroud the line 230 of that file and add this commands:
```
flags.delete_if { |x| x == "-fstack-protector-strong" }
flags << "-fstack-protector"
```

After a lot of reading, I found out that "-fstack-protector-strong" it's a new resource not implemented yet, but using "llvm-config --cflags", you see that this argument is present.

So, like others arguments, removed it during the compilation and replace for the old one that works "-fstack-prectector"

I believe that could it be a workaround and could it be set officially in this file running some kind of test like that:
```
clang -Wall -Wpedantic -fstack-protector-strong test.c
clang: error: unknown argument: '-fstack-protector-strong'
```
And checking for that error message.

**Comment by tak1n** [comment] 2015-10-17 14:37
Closing because of https://github.com/rubinius/rubinius/blob/master/CONTRIBUTING.md#version-managers

**Closed** 2015-10-17 18:48 UTC
Labels: Install

**Comment by matkoniecz** [comment] 2017-02-05 14:38
current link: https://github.com/rubinius/rubinius/blob/master/.github/contributing.md#version-managers

("Issues involving version managers will be closed if they can either not be reproduced when building from source, or when the original report makes no mention about the author having tried building from source.")
