### ISSUE TITLE
Crash report.

### ISSUE THREAD

**Issue by lumrandir** [rubinius/rubinius#2904] opened 2014-01-27 08:13 UTC
https://gist.github.com/anonymous/b0c207b64e8428fcbd54

**Comment by YorickPeterse** [comment] 2015-01-01 18:30
@lumrandir Any news on this, did you manage to find a way to reproduce the problem with the current Rbx release?

**Comment by lumrandir** [comment] 2015-01-02 07:37
@YorickPeterse  well, we've set aside the idea to use rubinius in production for a while, so no news on this. I think this issue should be closed for now.

**Comment by YorickPeterse** [comment] 2015-01-02 09:46
@lumrandir Is there anything you can share on the reasoning for not using Rubinius in production? If so, feel free to pop in IRC or discuss it here. I'll close this issue for the time being then, feel free to re-open if needed.

**Closed by YorickPeterse** 2015-01-02 09:46 UTC
Labels: crash, Needs feedback
