### ISSUE TITLE
Building rubinius fails when locale is set to "C"

### ISSUE THREAD

**Issue by nidev** [rubinius/rubinius#3389] opened 2015-05-03 13:11 UTC
With locale "C" (LANG="C" and LC_ALL="C"), building rubinius 2.5.3 and 2.5.2 fail during preinstalling gems for 2.1.0 with message:

``` text
[BUG: Control flow error in interpreter]
```

Full build log is here: [gist link](https://gist.github.com/nidev/c1d4cfc60d2c0ced755a)

Actual 'rbx' executable file is built successfully though, It behaves weirdly.

System Information:

``` text
Linux lrig-hanayo 4.0.1-gentoo #1 SMP Fri May 1 13:01:07 KST 2015 x86_64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz GenuineIntel GNU/Linux
rbenv 0.4.0-146-g7ad01b2
clang version 3.5.2 (tags/RELEASE_352/final)
Target: x86_64-pc-linux-gnu
Thread model: posix

nidev@lrig-hanayo /tmp/rubinius-2.5.3 % llvm-config --version                                                                                                                                                 
3.5.2

nidev@lrig-hanayo /tmp/rubinius-2.5.3 % /lib/libc.so.6                                                                                                                                                      
GNU C Library (Gentoo 2.20-r2 p4) stable release version 2.20, by Roland McGrath et al.
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.4.
Available extensions:
    C stubs add-on version 2.1.2
    crypt add-on version 2.1 by Michael Glad and others
    GNU Libidn by Simon Josefsson
    Native POSIX Threads Library by Ulrich Drepper et al
    BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.
```

I found similar build log from issue #2691. But this one seems different from #2691. I could resolve this problem by changing LANG to 'en_US.UTF-8'. and rebuilding rubinius cleanly. However, this error seems weird and I finally open this issue.

Procedure to reproduce this issue:
1. set LANG="C"
2. set LC_ALL="C"
3. unpack rubinius source
4. do ./configure
5. rake build
6. error occurs while preinstalling 2.1.0 gems

I couldn't find a word related to system locale on [rubinius build guide](http://rubini.us/doc/en/getting-started/building/). However, by setting LANG="en_US.UTF-8" and LC_ALL="en_US.UTF-8", 'rake build' worked fine.

I've checked this can be reproduced in Archlinux and Debian jessie. If I find simpler procedure, I will update it here.

Is there any special reason for this problem? Thanks.

**Comment by YorickPeterse** [comment] 2015-05-03 13:17
This is a fairly well known issue. Various parts of the pipeline require that LOCALE is set to something UTF-8-ish and will fail miserably if this is set to "C" or something similar. Other issues that experience the same problems are #2732 and #3275.

**Comment by nidev** [comment] 2015-05-03 13:22
@YorickPeterse Can we make rubinius warn if system locale is not UTF-8ish one? I mean, at least during build process.

**Comment by YorickPeterse** [comment] 2015-05-03 13:29
I'm not sure what we'd check against. If I'm not mistaken the locale doesn't _have_ to be UTF-8, but at least something that is more or less compatible. Some locales other than "C" might also trigger the same problem meaning the only accurate solution would be a massive whitelist of locales.

**Comment by nidev** [comment] 2015-05-03 13:35
@YorickPeterse I always appreciate your explanation. :smile:

It seems complicated issue. Then, can I keep this issue open and track updates and changes?

**Comment by YorickPeterse** [comment] 2015-05-03 13:37
Sure, ultimately we'll need to find a way so we can not enforce a specific locale, or at the very least we should document it somewhere.

**Comment by chuckremes** [comment] 2017-02-09 15:19
Just confirmed this issue still exists. When compiling on FreeBSD12 the LANG var is unset. This causes  gem verification to fail since some gem files contain author names with multi-byte characters. For whatever reason rubinius is still defaulting to US-ASCII instead of UTF-8. 

The fix is to `export LANG="en_US.UTF-8"` in the .profile (or suitable file for your shell) and rebuild.

**Comment by brixen** [comment] 2020-01-04 20:01
This should probably be fixed now:

```
$ rbx -v -e 'p Encoding.default_external'
rubinius 4.10.c12 (10.0 87356641 2020-01-04 9.0.0) [x86_64-darwin19.0.0]
#<Encoding:UTF-8>
```

**Closed by brixen** 2020-01-04 20:01 UTC
Labels: build
