### ISSUE TITLE
Date._parse has different arity than 1.9.3

### ISSUE THREAD

**Issue by wulftone** [rubinius/rubinius#2241] opened 2013-03-27 00:07 UTC
I ran into an issue with `Date._parse` using `ruby-american_date` where the arity of `_parse` caused some confusion.  In rbx's [time.rb](https://github.com/rubinius/rubinius/blob/release-2.0.0-rc1/lib/19/time.rb#L261), the arity of `_parse` is 3.

The confusion is from [here](https://github.com/jeremyevans/ruby-american_date/blob/1.1.0/lib/american_date.rb#L13-L18) where Jeremy is effectively replacing `_parse/3` with `_parse/2`, which is fine for MRI, but rbx proceeds to try and call `_parse/3` from the regular `parse` method from [time.rb](https://github.com/rubinius/rubinius/blob/release-2.0.0-rc1/lib/19/time.rb#L261).

I've made a fix for it and a spec that fails without my fix, but I'm not sure if the Rubinius team cares about preserving the arity of each function in MRI...?

**Comment by YorickPeterse** [comment] 2015-02-18 17:05
Do we have any repro for this, and does the problem still occur to begin with?

**Comment by mjc** [comment] 2015-03-02 16:47
IIRC loading the american date gem and then trying to do ```Date.parse("01/02/2013")``` would trigger it.

**Comment by YorickPeterse** [comment] 2015-07-30 21:54
I can't reproduce this using the following:

```
gem install american_date
ruby -r american_date -e 'Date.parse("01/02/2013")'
```

Closing this as there's no other reliable way to reproduce this as far as I can tell. Feel free to re-open if the issue still persists and there's a way for us to reproduce it.

**Closed by YorickPeterse** 2015-07-30 21:54 UTC
Labels: Needs feedback
