### ISSUE TITLE
Incorrect parameter passed to inject inside each block

### ISSUE THREAD

**Issue by bjfish** [rubinius/rubinius#3325] opened 2015-02-20 18:14 UTC
The following w and h variables inside the inject are incorrectly being set to the width and heigh params of the each block:

rbx-2.5.2

```ruby
[[8, 8]].each { | (width, height) | puts [[1, 1], [1, 1], [2, 1], [2, 2], [4, 2], [4, 4], [8, 4]].inject(0) { |sum, (w, h)| puts "w #{w} h #{h}"; sum + (w*h) } }
w 8 h 8
w 8 h 8
w 8 h 8
w 8 h 8
w 8 h 8
w 8 h 8
w 8 h 8
448
=> [[8, 8]]
```

Expected result:

ruby-2.1

```ruby
2.1.5 :001 > [[8, 8]].each { | (width, height) | puts [[1, 1], [1, 1], [2, 1], [2, 2], [4, 2], [4, 4], [8, 4]].inject(0) { |sum, (w, h)| puts "w #{w} h #{h}"; sum + (w*h) } }
w 1 h 1
w 1 h 1
w 2 h 1
w 2 h 2
w 4 h 2
w 4 h 4
w 8 h 4
64
 => [[8, 8]]
```

**Comment by YorickPeterse** [comment] 2015-02-20 19:33
What is the expected output/behaviour in this case?

**Comment by bjfish** [comment] 2015-02-20 21:39
@YorickPeterse I've added the expected output above.

**Comment by YorickPeterse** [comment] 2015-02-20 21:59
Hm, interesting. If you're up for it you can write a spec. Doing so in https://github.com/rubinius/rubinius/blob/master/spec/ruby/core/enumerable/shared/inject.rb is probably the best, although the file currently looks a bit daunting. If possible try to trim down the spec to the bare minimum required to reproduce the problem, right now the example is a bit difficult to read due to the length.

**Comment by bjfish** [comment] 2015-02-21 16:48
@YorickPeterse a little shorter example 
```ruby
total = 0
[[1,1]].each { | (one1, one2) | total = [[2,2]].inject(0) { |sum, (two1, two2) | sum + (two1 + two2) } }
total == 4
```

**Comment by ahmadsherif** [comment] 2016-02-29 20:13
Seems to be the same as #3544. The snippet given doesn't reproduce now anyway, so closing as fixed.

**Closed by ahmadsherif** 2016-02-29 20:13 UTC
Labels: Compatibility
