### ISSUE TITLE
ERROR:  While executing gem ... (ArgumentError) method 'read_nonblock': given 3, expected 2

### ISSUE THREAD

**Issue by mangas** [rubinius/rubinius#3501] opened 2015-09-04 19:58 UTC
$ which gem && gem install --backtrace bundler
/usr/bin/gem
ERROR:  While executing gem ... (ArgumentError)
    method 'read_nonblock': given 3, expected 2
	/home/user/rubies/rubinius/2.5.8/gems/gems/rubysl-openssl-2.3.0/lib/openssl/buffering.rb:182:in `read_nonblock'
	/home/user/rubies/rubinius/2.5.8/gems/gems/rubysl-net-protocol-2.0.1/lib/rubysl/net/protocol/protocol.rb:153:in `rbuf_fill'
	/home/user/rubies/rubinius/2.5.8/gems/gems/rubysl-net-protocol-2.0.1/lib/rubysl/net/protocol/protocol.rb:134:in `readuntil'
	/home/user/rubies/rubinius/2.5.8/gems/gems/rubysl-net-protocol-2.0.1/lib/rubysl/net/protocol/protocol.rb:144:in `readline'
	/home/user/rubies/rubinius/2.5.8/gems/gems/rubysl-net-http-2.0.4/lib/net/http/response.rb:39:in `read_status_line'
	/home/user/rubies/rubinius/2.5.8/gems/gems/rubysl-net-http-2.0.4/lib/net/http/response.rb:28:in `read_new'
	/home/user/rubies/rubinius/2.5.8/gems/gems/rubysl-net-http-2.0.4/lib/rubysl/net/http/http.rb:914:in `connect'
	/home/user/rubies/rubinius/2.5.8/gems/gems/rubysl-net-http-2.0.4/lib/rubysl/net/http/http.rb:862:in `do_start'
	/home/user/rubies/rubinius/2.5.8/gems/gems/rubysl-net-http-2.0.4/lib/rubysl/net/http/http.rb:857:in `start'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/request/http_pool.rb:42:in `setup_connection'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/request/https_pool.rb:6:in `setup_connection'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/request/http_pool.rb:38:in `make_connection'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/request/http_pool.rb:19:in `checkout'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/request.rb:85:in `connection_for'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/request.rb:140:in `perform_request'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/request.rb:109:in `fetch'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/remote_fetcher.rb:352:in `request'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/remote_fetcher.rb:237:in `fetch_https (fetch_http)'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/remote_fetcher.rb:273:in `fetch_path'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/source.rb:91:in `dependency_resolver_set'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/resolver/best_set.rb:23:in `pick_sets'
	kernel/bootstrap/array.rb:76:in `each'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/source_list.rb:97:in `each_source'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/resolver/best_set.rb:22:in `pick_sets'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/resolver/best_set.rb:28:in `find_all'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/resolver/installer_set.rb:151:in `find_all'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/resolver/installer_set.rb:54:in `add_always_install'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/dependency_installer.rb:473:in `resolve_dependencies'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/commands/install_command.rb:238:in `install_gem'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/commands/install_command.rb:299:in `install_gems'
	kernel/bootstrap/array.rb:76:in `each'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/commands/install_command.rb:295:in `install_gems'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/commands/install_command.rb:202:in `execute'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/command.rb:307:in `invoke_with_build_args'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/command_manager.rb:168:in `process_args'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/command_manager.rb:138:in `run'
	/home/user/rubies/rubinius/2.5.8/library/rubygems/gem_runner.rb:54:in `run'
	/home/user/rubies/rubinius/2.5.8/library/bin/gem.rb:21:in `__script__'
	kernel/delta/code_loader.rb:66:in `load_script'
	kernel/delta/code_loader.rb:152:in `load_script'
	kernel/loader.rb:656:in `script'
	kernel/loader.rb:842:in `main'

**Comment by mangas** [comment] 2015-09-04 23:29
This issue might reproducible by adding the following bash environment variables
```
export HTTP_PROXY=http://127.0.0.1:3128
export http_proxy=http://127.0.0.1:3128
```
and trying to install a gem
```
gem install bundler
```

**Comment by brixen** [comment] 2015-09-04 23:37
@mangas thanks for the help repro'ing this. After pulling down a fedora 22 vagrant image and building Rubinius, the issue does not manifest. After setting up the proxy you described, I can repro it:

```
$ dnf install squid
$ systemctl start squid.service
$ export HTTP_PROXY=http://127.0.0.1:3128
$ export http_proxy=http://127.0.0.1:3128
$ gem install bundler
ERROR:  While executing gem ... (ArgumentError)
    method 'read_nonblock': given 3, expected 2
```

I'll investigate.

**Comment by brixen** [comment] 2015-09-05 00:13
When the proxy env vars are set, [this conditional](https://github.com/rubysl/rubysl-openssl/blob/2.0/ext/rubysl/openssl/ossl_ssl.c#L1420) is false and [this method call](https://github.com/rubysl/rubysl-openssl/blob/2.0/ext/rubysl/openssl/ossl_ssl.c#L1456) is made on an instance of `TCPSocket` whose `read_nonblock` method is defined in `IO (kernel/common/io.rb:1873)`

For MRI 2.2, `ri TCPSocket#read_nonblock` gives:

```
= TCPSocket#read_nonblock

(from ruby core)
=== Implementation from IO
------------------------------------------------------------------------------
  ios.read_nonblock(maxlen)              -> string
  ios.read_nonblock(maxlen, outbuf)      -> outbuf

------------------------------------------------------------------------------

Reads at most maxlen bytes from ios using the read(2) system
call after O_NONBLOCK is set for the underlying file descriptor.

If the optional outbuf argument is present, it must reference a
String, which will receive the data. The outbuf will contain only
the received data after the method call even if it is not empty at the
beginning.

read_nonblock just calls the read(2) system call. It causes all errors the
read(2) system call causes: Errno::EWOULDBLOCK, Errno::EINTR, etc. The caller
should care such errors.

If the exception is Errno::EWOULDBLOCK or Errno::AGAIN, it is extended by
IO::WaitReadable. So IO::WaitReadable can be used to rescue the exceptions for
retrying read_nonblock.
...
```
So, it looks correct that on Rubinius, TCPSocket is inheriting the method from IO. That leaves the conditional being the cause of the difference when the proxy env vars are set.

It also raises the question whether that else branch is a bug even on MRI.

I haven't investigated the why the conditional is different yet.

**Comment by brixen** [comment] 2015-09-05 00:22
MRI 2.2.2, at least, raises if you call `IO#read_nonblock` with 3 arguments, so either that code is a bug or in MRI, the call is not on an instance of IO (or TCPSocket). Changing the method call linked above to pass 2 arguments results in the gem installing with the proxy env vars set.

**Comment by Grace** [comment] 2015-11-13 00:54
I had the same problem. @brixen I will try to fix it with your suggestion.

     rbx gem install bundler
     ERROR:  While executing gem ... (ArgumentError)
         method 'read_nonblock': given 3, expected

**Comment by Mazwak** [comment] 2016-01-13 11:12
MRI accepts 3 arguments. However, the third one is a named parameter, and is not documented.

From rubinius source, we clearly see that it is not handled :

**Comment by ahmadsherif** [comment] 2016-03-06 21:26
`IO#read_nonblock` now accepts `exception` option, so closing as fixed.

**Closed by ahmadsherif** 2016-03-06 21:26 UTC
