### ISSUE TITLE
Implicit `super` call fails with double splat

### ISSUE THREAD

**Issue by robin850** [rubinius/rubinius#3471] opened 2015-07-18 21:23 UTC
Hello,

There's a tiny bug when calling `super` without explicitly specifying the argument using the double splat:

~~~ruby
class Foo
  def foo(**options)
  end
end

class Bar < Foo
  def foo(**options)
    super
  end
end

Bar.new.foo
~~~

will raise:

~~~
method 'foo': given 1, expected 1 (ArgumentError)
~~~

Have a nice day.

**Comment by YorickPeterse** [comment] 2015-07-18 21:47
Probably the same problem as described in #3295.

**Comment by YorickPeterse** [comment] 2015-07-24 15:49
Closing as a duplicate of #3363

**Closed by YorickPeterse** 2015-07-24 15:49 UTC
