### ISSUE TITLE
jit crash

### ISSUE THREAD

**Issue by washu** [rubinius/rubinius#3281] opened 2015-01-12 17:53 UTC
puma 2.9.2 (unix:///usr/local/aztec-ui-staging/tmp/puma/puma.sock): /usr/include/llvm/Support/Casting.h:97: static bool llvm::isa_impl_cl<llvm::Constant, const llvm::Value *>::doit(const From *) [To = llvm::Constant, From = const llvm::Value *]: Assertion `Val && "isa<> used on a null pointer"' failed.
The Rubinius process is aborting with signal: SIGABRT

**Comment by jc00ke** [comment] 2015-01-12 17:58
Looks like a duplicate of #3249.

@washu next time, please provide more info: [CONTRIBUTING](https://github.com/rubinius/rubinius/blob/master/CONTRIBUTING#L7-L25) so we can help debug and fix the issue.

**Closed by jc00ke** 2015-01-12 17:58 UTC
