### ISSUE TITLE
Failing test suite on Travis on rbx-2.2.6

### ISSUE THREAD

**Issue by lothar59** [rubinius/rubinius#2973] opened 2014-03-11 11:25 UTC
Hi,
I have the following when running my test suite on travis on the version 2.2.6 of rbx.
It was passing on rbx-2.2.5 and before though.

undefined method empty?' on nil:NilClass.
(in /home/travis/build/ocs-pjt/ocs/app/assets/stylesheets/application.css.scss)
`
 kernel/delta/kernel.rb:78:in empty? (method_missing)'
 kernel/common/mutex.rb:8:in marshal_dump'
 kernel/common/marshal.rb:1062:in serialize_user_marshal'
 kernel/common/marshal.rb:905:in serialize'
...
`

**Comment by YorickPeterse** [comment] 2015-02-18 19:27
Does this problem still occur on Rubinius 2.5.2? If so, could you provide a way for us to reproduce the problem?

**Comment by johnmuhl** [comment] 2015-02-18 20:35
@YorickPeterse I re-ran that old build or mine and it's working now. Seems like it was probably a Travis issue.

**Comment by YorickPeterse** [comment] 2015-07-30 22:00
Closing this due to it apparently working again (as per above comment). If the issue still persists feel free to re-open.

**Closed by YorickPeterse** 2015-07-30 22:00 UTC
Labels: Needs feedback
