### ISSUE TITLE
JIT problem

### ISSUE THREAD

**Issue by hosiawak** [rubinius/rubinius#2471] opened 2013-07-19 15:22 UTC
Running the Red black tree benchmark 4 out of 5 times results in https://gist.github.com/hosiawak/6039750

Running with -Xint always completes which suggest it's a problem with the JIT.

**Comment by brixen** [comment] 2015-01-25 22:31
@hosiawak I haven't been able to reproduce this on 2.5.0 running many times. If you are able to reproduce it, could you run with `-Xjit.debug -Xjit.inline.debug -Xjit.show -Xjit.sync` and include a gist of the output?

Closing this due to the age of the ticket because a lot of JIT and VM work has been done in the interim. Please re-open if you can provide the info above.

**Closed by brixen** 2015-01-25 22:31 UTC
Labels: JIT
