### ISSUE TITLE
[BUG: Unable to lock object]

### ISSUE THREAD

**Issue by ghazel** [rubinius/rubinius#3043] opened 2014-05-22 23:27 UTC
Trying to reproduce #3025 I found another bug:

```C++
[BUG: Unable to lock object]
.ruby(_ZN8rubinius3bugEPKc+0x43) [0x5a03b3] 
ruby() [0x64c052] 
ruby(_ZN8rubinius5Class9auto_packEPNS_5StateERNS_11GCTokenImplEPNS_9CallFrameE+0x84) [0x688884] 
ruby(_ZN8rubinius5Class8allocateEPNS_5StateERNS_11GCTokenImplEPNS_9CallFrameE+0x3f2) [0x689ac2] 
ruby(_ZN8rubinius10Primitives14class_allocateEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+0xbc) [0x637a5c] 
ruby(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x25df) [0x5bd19f] 
ruby(_ZN8rubinius11MachineCode19execute_specializedINS_17SplatOnlyArgumentEEEPNS_6ObjectEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+
0x280) [0x5fc300] 
ruby(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x16c1) [0x5bc281] 
ruby(_ZN8rubinius11MachineCode19execute_specializedINS_16GenericArgumentsEEEPNS_6ObjectEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+0
x21c) [0x5fa76c] 
ruby(_ZN8rubinius12CompiledCode16default_executorEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+0xc7) [0x68afa7] 
ruby(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x25df) [0x5bd19f] 
ruby(_ZN8rubinius11MachineCode19execute_specializedINS_11NoArgumentsEEEPNS_6ObjectEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+0x1f4)
 [0x5fc6d4] 
ruby(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x25df) [0x5bd19f] 
ruby(_ZN8rubinius11MachineCode19execute_specializedINS_12TwoArgumentsEEEPNS_6ObjectEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+0x2c4
) [0x5fb964] 
ruby(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x25df) [0x5bd19f] 
ruby(_ZN8rubinius11MachineCode19execute_specializedINS_11NoArgumentsEEEPNS_6ObjectEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+0x1f4)
 [0x5fc6d4] 
ruby(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x298c) [0x5bd54c] 
ruby(_ZN8rubinius11MachineCode19execute_specializedINS_11NoArgumentsEEEPNS_6ObjectEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+0x1f4)
 [0x5fc6d4] 
ruby(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x28a7) [0x5bd467] 
ruby(_ZN8rubinius11MachineCode19execute_specializedINS_14ThreeArgumentsEEEPNS_6ObjectEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+0x2
cc) [0x5fb46c] 
ruby(_ZN8rubinius11MachineCode11interpreterEPNS_5StateEPS0_PNS_20InterpreterCallFrameE+0x28a7) [0x5bd467] 
ruby(_ZN8rubinius11MachineCode19execute_specializedINS_16GenericArgumentsEEEPNS_6ObjectEPNS_5StateEPNS_9CallFrameEPNS_10ExecutableEPNS_6ModuleERNS_9ArgumentsE+0
x21c) [0x5fa76c] 
[0x7f535fdd68ad]                                                                                                 
```

My lame repro script (the idea is that Thread.raise is involved in the original bug because Net::HTTP uses Timeout.timeout)
```ruby
require 'httparty'
require 'json'

class GCM
  include HTTParty
  PUSH_URL = 'https://android.googleapis.com/gcm/send'
  base_uri PUSH_URL
  default_timeout 30
  format :json

  def send
    params = {
      :body => {}.to_json,
      :headers => {
        'Content-Type' => 'application/json',
      }
    }
    response = self.class.post('', params)
  end
end

threads = []
10.times do
  threads << Thread.new do
    begin
      gcm = GCM.new
      loop do
        begin
          print '.'
          gcm.send.code
        rescue
        end
      end
    rescue
      retry
    end
  end
end

loop do 
  threads.each do |t|
    t.raise "foo"
  end
end
```

**Comment by YorickPeterse** [comment] 2015-01-01 18:36
Closing this, I can't reproduce this on the current master branch using the above script. Feel free to re-open if the issue still persits or re-manifests.

**Closed by YorickPeterse** 2015-01-01 18:36 UTC
Labels: crash
