### ISSUE TITLE
MRI vs Rubinius autoloading difference

### ISSUE THREAD

**Issue by akhramov** [rubinius/rubinius#3769] opened 2017-11-12 15:04 UTC
Hi, thank you for your awesome work.

Rubinius and MRI handle autoloading differently. When interpreter loads a file of the autoloaded module, `Module#const_defined?` returns false in MRI, but true in Rubinius. Same goes for `defined?` keyword.

I have created a reproduction repo:
https://github.com/akhramov/autoload-repro

I'm sorry if this issue is filed somewhere already.
Thanks!

**Comment by brixen** [comment] 2017-11-12 18:15
@akhramov this is really interesting, thanks for opening the issue. I'm reworking `require` and our compilation caching right now, so I'll take a look at this.

**Comment by brixen** [comment] 2018-01-19 05:28
@akhramov unfortunately, the issue is more complex than the repro, as far as I can tell.

In the Bundler issue, the constant is not being resolved via autoload, but rather via require. In this context, MRI returns different things for `class Foo; defined?(Bar); end' and for `class Foo; defined?(Foo::Bar); end`.

I'm still investigating, so reopening this.

**Comment by brixen** [comment] 2018-01-19 07:05
@akhramov fwiw, I'm working on a repro here: https://github.com/brixen/autoload

Current status:

```
$ chruby 2.4
$ ruby -v a.rb > mri_2.4.txt
$ chruby rbx
$ ruby -v a.rb > rbx.txt
$ diff mri_2.4.txt rbx.txt
1c1
< ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
---
> rubinius 3.92.c3 (2.3.1 510c30f7 2018-01-18 5.0.0) [x86_64-darwin17.3.0]
31c31
< "constant"
---
> nil
51c51
< "constant"
---
> nil
```

**Comment by brixen** [comment] 2018-01-19 20:12
@akhramov ok, looks like it comes down to this: when the snippet of code below is in a file for which an autoload for `A::E` is defined, when the file is loaded, either via require or autoload trigger, the results in comments will be computed. If that code were not in the file being required, all those `nil`s would be `"constant"`s and those `false`s would be `true`s (as can be seen [here](https://github.com/brixen/autoload/blob/master/c.rb))

The asymmetry between `defined? B` vs `defined? A::B` when in class A, and for `defined? B` between class A and class AA is unfortunate, probably unintentional (is there a good argument for it?), probably a bug (who knows?).

I'll give you my unvarnished opinion on this, fwiw (and perhaps you can take it to other projects like Bundler if it makes sense): neither `autoload` nor `defined?` should ever be used.

Autoload adds nothing but indeterminacy to code ("I moved this constant expression, why did my code loading order change?"), and can in all cases be replaced by conditional requires. `defined?` is literally a partial evaluator for parse trees and in all cases that I'm aware of can be replaced by computing with methods exposed on objects (if there are cases that cannot be so replaced, I'd like to see them as they suggest useful methods that are missing).

That said, I'll figure out how to mimic this behavior.

```ruby
class A
  p defined? E              # => "constant"
  p defined? A::E           # => nil
  puts

  p A.const_defined? :E     # => false
  p const_defined? :E       # => false
  puts
end

p defined? A::E             # => nil
puts

p A.const_defined? :E       # => false
puts

class AA < A
  p defined? E              # => nil
  p defined? A::E           # => nil
  puts

  p A.const_defined? :E     # => false
  p const_defined? :E       # => false
  puts
end
```

**Comment by brixen** [comment] 2018-01-19 22:44
Another fun fact about autoload: if the file for which an autoload is defined happens to be loaded by `load`, use of the autoload-defined constant in that file will trigger `require` of the file while `load` is in the process of loading it.

**Comment by akhramov** [comment] 2018-01-20 05:12
Hi @brixen, it looks like we have discovered the darkest part of MRI I've ever seen.

While I tend to agree that `defined?` should be avoided, I used `autoload` for the single purpose: lazy loading. Users of a library might not want the whole set of functionality and therefore there's no need to load all at once.

Thank you for the test suite. I'm going to run it on different versions of Ruby to see if it's a regression of any kind. It's also interesting how other Ruby implementations handle this case.

I'll keep you posted.

**Comment by akhramov** [comment] 2018-01-20 09:03
Nope, it looks like MRI always had the same autoload behavior (I checked on 1.9.3).
Other major Ruby implementations also suffer from the same problem.

Is there any way I can help further?

**Comment by chuckremes** [comment] 2018-01-20 14:13
If you are looking for lazy loading, force that back onto the user. Make them decide, via require, just how much to load.

For example:

# load entire library
require ‘mylibrary’

# load base framework
require ‘mylibrary/skeleton’

# load 3 main pieces
require ‘mylibrary/object1’ # any of these also require ‘mylibrary/skeleton'
require ‘mylibrary/object2’
require ‘mylibrary/object3’

etc.

Yes, it isn’t as terse and it puts more burden on the library user but it’s also less error prone. You’ll know pretty quickly if you screwed up because you’ll get exceptions when referring to classes/modules that weren’t loaded.

That said, I’m certain @brixen could devise a superior and simpler mechanism that doesn’t have all the same odd rabbit-holes as the Ruby autoload feature. He’s done most of that with the `codedb` mechanism but that’s a Rubinius-only feature.

**Comment by brixen** [comment] 2018-01-20 17:51
@akhramov you've helped a ton by 1. opening the issue, and 2. putting effort into the initial repro. That was a huge help in pointing me in an initial direction. Very much appreciated. For Rubinius, I'm wrapping up a fix now.

The thing that probably bugs me the most is the asymmetry between `defined? E` and `defined? A::E` under the autoload context.

See [this commit](https://github.com/brixen/autoload/commit/8c53766db25173d6d9ccb62ee78fdf09b3b24a18) where I try to illustrate more clearly the consequence of "scope constant resolution" and "path constant resolution".

Note how the placement chosen for class AAA changes the result of code _that looks exactly the same_! Ruby doesn't have a Ruby object that represents lexical scope (like the Rubinius LexicalScope object), so there is nothing tangible to point a Ruby programmer to for help in understanding this difference, and this is potentially a major confusion for a Ruby programmer.

As for your use of autoload for lazy loading, it's possible to do that via `const_missing`, which I believe is still the approach that Rails uses (but I'm not positive). You have a completely legitimate concern and its a concern that I'm treating as a first class consideration in Rubinius.

I've added the CodeDB, which is both a physical and logical entity. Code is cached into the CodeDB (or pre-cached in the case of the Ruby core library) and is loaded lazily, not on the granularity of a single Ruby file, but rather on the granularity of a single Ruby method. I've not yet finished implementing the caching of non-core code, but that's coming soon.

CodeDB is also a logical entity because every executable context (eg Ruby file, class or module body, method, block) has a unique ID. That ID can be used to associate arbitrary dimensions of data with the executable code, for example, source code, AST, optimized bytecode, LLVM IR, coverage data, profiling data, runtime type information, and likely more.

I hope you'll check it out sometime 😄

**Closed** 2018-01-20 19:51 UTC

**Comment by akhramov** [comment] 2018-01-21 07:29
Thank you, @brixen, I'll check the CodeDB right away!
