### ISSUE TITLE
Can't install/upgrade through RVM

### ISSUE THREAD

**Issue by RoxasShadow** [rubinius/rubinius#3703] opened 2016-10-14 08:25 UTC
## Problem

I'm trying to upgrade rbx-3.30 to rbx-3.60 through the latest RVM (both stable and head) on a Debian machine.

I had three errors related to missing gems (iirc they were redcard, rubinius/code/trigger and melbourne) that I solved by installing them in ruby-2.3.1.

But still, after these errors went away, the installation didn't proceed because of an error by melbourne.
## How to Reproduce

`$ rvm upgrade rbx-3.30 rbx-3.60`

But right now I can't even run `$ rvm install rbx-3.60` as I get the same error every time.
## Configuration Details

```
▶ uname -a
Linux ns319168.ip-91-121-209.eu 3.14.32-xxxx-grs-ipv6-64 #1 SMP Sat Feb 7 11:35:27 CET 2015 x86_64 GNU/Linux
```

```
▶ rvm -v
rvm 1.27.0 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

```

```
▶ rvm list

rvm rubies

   rbx-2.5.8 [ x86_64 ]
=* rbx-3.30 [ x86_64 ]
   ruby-2.2.0 [ x86_64 ]
   ruby-2.3.1 [ x86_64 ]
```
## Stack Trace

https://gist.github.com/RoxasShadow/f28cfb9269b41c49456c4dee163e8b71

**Comment by brixen** [comment] 2016-10-14 16:24
@RoxasShadow thanks for reporting this issue. Unfortunately, we cannot help you debug RVM, but we can try to figure out if the issue is in Rubinius. Please see the directions under ["Building from Source Code"](https://book.rubinius.com/manuscript/getting_rubinius.html).

If you're able to build Rubinius from source, you can file an issue with RVM for the problem. If you cannot build Rubinius from source, we should be able to fix your issue.

**Comment by RoxasShadow** [comment] 2016-10-14 17:19
Thanks for the suggestion @brixen. Asking RVM to install Rubinius from the tarball, I managed to make it work.

**Comment by RoxasShadow** [comment] 2016-10-14 17:35
Actually that's not true, at the very end the compilation of Rubinius by tarball failed!

[Stacktrace](https://gist.github.com/RoxasShadow/1ac63b9523e06536f240da83411e0aa1)

**Comment by brixen** [comment] 2016-10-14 18:24
@RoxasShadow the version of the Rubinius compiler needed to build 3.61 is not compatible with 3.30. Try using MRI 2.3 as your build Ruby.

**Comment by RoxasShadow** [comment] 2016-10-14 20:18
Switched to MRI 2.3.1 and run `bundle install`, `bundle exec rake clean`  and `bundle exec rake build`. [Output](https://gist.github.com/RoxasShadow/db0be1fc2c0d7e4f7166a64a2713af33)

**Comment by brixen** [comment] 2016-10-14 22:48
@RoxasShadow thanks for running through those manual steps. Could you rebuild using `./configure --debug-build` and use `bundle exec rake build --trace` and when it fails, try running this (you may need to install lldb package first) `lldb -f /home/deployer/rbx/rubinius-3.61/bin/rbx -- -v`.

**Comment by RoxasShadow** [comment] 2016-10-15 00:13
@brixen [here's](https://gist.github.com/RoxasShadow/decd8a9d9fb0ea6ee8582bf782ea6a98) the output. Thanks.

**Comment by brixen** [comment] 2016-10-15 04:14
@RoxasShadow oops! I forgot to say, type `r` Enter in lldb. :(

**Comment by RoxasShadow** [comment] 2016-10-15 09:51
Oh, that's why!

```
deployer@ns319168:~                                                           ⍉
▶ lldb -f /home/deployer/rbx/rubinius-3.61/bin/rbx -- -v
(lldb) target create "/home/deployer/rbx/rubinius-3.61/bin/rbx"
Current executable set to '/home/deployer/rbx/rubinius-3.61/bin/rbx' (x86_64).
(lldb) settings set -- target.run-args  "-v"
(lldb) r
Process 23306 launched: '/home/deployer/rbx/rubinius-3.61/bin/rbx' (x86_64)
Process 23306 stopped
* thread #1: tid = 23306, 0x00000000004d5ac3 rbx`std::basic_regex<char, std::regex_traits<char> >::assign(this=0x00007ea050add6d8, __rhs=0x00007ea050adcc68) + 147 at regex.h:625, name = 'rbx', stop reason = signal SIGILL: illegal instruction operand
    frame #0: 0x00000000004d5ac3 rbx`std::basic_regex<char, std::regex_traits<char> >::assign(this=0x00007ea050add6d8, __rhs=0x00007ea050adcc68) + 147 at regex.h:625
   622 		_M_flags = __rhs._M_flags;
   623 		_M_original_str = std::move(__rhs._M_original_str);
   624 		__rhs._M_automaton.reset();
-> 625 		this->imbue(__rhs.getloc());
   626 	      }
   627
   628 	      /**
```

**Comment by brixen** [comment] 2016-10-15 16:51
@RoxasShadow awesome, this is super helpful. Could you run one more command after `r` stops: `thread backtrace all` and gist that?

**Comment by RoxasShadow** [comment] 2016-10-16 09:23
@brixen sure, [this is](https://gist.github.com/RoxasShadow/786856ca5c796baca72d8d9d236ac6f6) the gist. Thanks!

**Comment by brixen** [comment] 2016-10-16 16:27
@RoxasShadow thanks for running that. Unfortunately, it doesn't tell me anything more than the C++ regex implementation is segfaulting on one of the default Rubinius configuration values. This appears to be an issue with your platform. Could you give me all the details so I can try to get a similar vagrant box and repro it locally?

**Comment by RoxasShadow** [comment] 2016-10-16 17:28
@brixen which kind of details do you need?

It's a Kimsufi/OVH server machine running Debian 8.6 with gcc 4.9.2 and LLVM 3.7.1. In the original post you can check the `uname` too.

**Comment by brixen** [comment] 2016-10-16 21:27
@RoxasShadow ok, cool. Thanks. Let me try to get a machine set up so I can test this.

**Comment by brixen** [comment] 2016-11-05 01:48
@RoxasShadow I'm having trouble getting a Debian 8 box set up. Will continue to work on it.

**Comment by brixen** [comment] 2020-01-03 05:39
I think Debian is on version 11 or something now, so I'm going to close this.

**Closed by brixen** 2020-01-03 05:39 UTC
