### ISSUE TITLE
Kernel(Rubinius::Loader)#message (method_missing) when compiling rbx 2.5.2

### ISSUE THREAD

**Issue by pxlpnk** [rubinius/rubinius#3307] opened 2015-02-03 12:59 UTC
I tried to install rbx 2.5.2 on OSX 10.9.5 but it fails with the following:
```bash
undefined local variable or method `message' on an instance of Rubinius::Loader. (NameError)

Backtrace:

  Kernel(Rubinius::Loader)#message (method_missing) at kernel/delta/kernel.rb:78
                     Rubinius::Loader#load_compiler at kernel/loader.rb:558
                              Rubinius::Loader#main at kernel/loader.rb:798
```

The steps to reproduce:
```bash
git checkout v2.5.2
```

```bash
./configure --prefix=$HOME/.rbenv/versions/rbx-2.5.2-git \
                  --cc=clang \
                  --cxx=clang++ 
                  --llvm-config=/usr/local/Cellar/llvm/3.5.1/bin/llvm-config
```

```bash
rake install
```
I wanted to install it from source into the rbenv environment. Could it be that `rbenv 0.4.0` has any influence on this?
The same problem happens with:
`ruby 1.9.3p545 (2014-02-24 revision 45159) [x86_64-darwin13.1.0]`
and
`ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]`

See the attached gist with the outputs of commands and the `config.rb` and `configure` files
[Gist:pxlpnk/6b8efbcadd7f54dd13d3](https://gist.github.com/pxlpnk/6b8efbcadd7f54dd13d3)

Please let me know what additonal information can help.

**Comment by brixen** [comment] 2015-02-03 15:53
This is fixed in master d759bfd91885be83b5534e97904ea0da7939ae5e

**Closed by brixen** 2015-02-03 15:53 UTC
Labels: Install

**Comment by YorickPeterse** [comment] 2015-02-03 15:55
@brixen Not so sure about that, we tried compiling from source during FOSDEM (Sunday to be exact) and we were still running into this particular problem.

**Comment by brixen** [comment] 2015-02-03 17:55
@pxlpnk I just installed llvm 3.5.1 and rebuilt Rubinius on 10.10 with no issue. Unsure where to go from here for debugging this.

**Comment by pxlpnk** [comment] 2015-02-03 18:20
The same things happen when using my system ruby (`ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]`). 
So I think `rbenv` should not be the issue here. I have no idea either where to look. It seems that everything 2.5.x is not building. Haven't tested anything pre 2.5.0.

Seems like something on my system is broken. Thank you for your help. 
Do you want to proceed investigating this issue?

**Comment by brixen** [comment] 2015-02-03 23:29
> Do you want to proceed investigating this issue?

Well, it's a confusing issue, for sure. I'm not finding any clear solution from googling and I can't reproduce it.

If you need to build Rubinius from source, we need to figure out what the issue is. If you just need to use Rubinius, we build binaries for OS X 10.8+ every release, so if we can make those more convenient for you (ie making them work with rbenv like they do with chruby), that's a better use of my time.

If you want to open a separate issue for the  `__ZNSs4_Rep20_S_empty_rep_storageE` symbol not found, it would probably be easier to track.

**Comment by YorickPeterse** [comment] 2015-02-04 00:14
It's worth mentioning I've experienced this same error a few times myself. However, every time I could solve the problem by removing the target installation directory and running `rake install` again. Having said that, the particular problem occurs very rarely so I'm not sure how to trigger it reliably.

**Comment by brixen** [comment] 2015-02-04 00:18
@YorickPeterse ah, very interesting that you've seen it. If you see it again, could you `nm` all the object files to look for where this symbol occurs?

**Comment by YorickPeterse** [comment] 2015-02-04 00:22
@brixen Will do

**Comment by pxlpnk** [comment] 2015-02-04 06:42
I did some more research yesterday and built rubinius on my system with a new user and all of a sudden it worked. So I went trough my configs and found this:
```bash
export CC=/usr/local/Cellar/apple-gcc42/4.2.1-5666.3/bin/gcc-4.2
export CXX=/usr/local/Cellar/apple-gcc42/4.2.1-5666.3/bin/g++-4.2
export CPP=/usr/local/Cellar/apple-gcc42/4.2.1-5666.3/bin/cpp-4.2
```
Which I added a year ago because homebrew would not build anything iirc.
Sorry for the troubles.

**Comment by brixen** [comment] 2015-02-04 15:45
@pxlpnk oh, great to hear it's working! It's really confusing that clang reports as 4.2 so you can't easily tell which one the system is using.

**Comment by saizai** [comment] 2015-02-07 20:05
@brixen When will this get into a version bump / rvm? (I'm seeing this in some errors in production.)

**Comment by brixen** [comment] 2015-02-07 20:20
@saizai very soon, hopefully Monday latest.

**Comment by saizai** [comment] 2015-02-08 14:13
@brixen Thanks! Would you mind pinging on this thread when it's bumped?

**Comment by brixen** [comment] 2015-02-08 18:38
@saizai unfortunately, I'll probably forget, but I announce releases on https://twitter.com/rubinius. I'm open to suggestions for a better release notification mechanism. Maybe a specific RSS/Atom release feed at http://rubini.us?

**Comment by jc00ke** [comment] 2015-02-08 20:59
If there's an RSS feed for tags on GitHub we can set up an RSS-to-email newsletter.

**Comment by johnmuhl** [comment] 2015-02-08 21:45
@jc00ke there is https://github.com/rubinius/rubinius/releases.atom

**Comment by brixen** [comment] 2015-02-08 22:32
@johnmuhl oh sweet, thanks! I was looking all over the UI for that.

**Comment by jc00ke** [comment] 2015-02-09 18:28
Check out https://feed.press/ too, in case we want to set that up for those that don't use RSS.

**Comment by saizai** [comment] 2015-03-15 17:57
@brixen Still not bumped per rvm?
