### ISSUE TITLE
Omniauth undefined method `encoding' on nil:NilClass.

### ISSUE THREAD

**Issue by kevinzhow** [rubinius/rubinius#2765] opened 2013-11-05 06:21 UTC
After I migrate my app tp Puma + Rubinius
When I oauth twitter, after it redirect back, will have this error

```
Started GET "/auth/twitter" for xxx.xxx.xxx.xxx at 2013-11-05 06:12:42 +0000

NoMethodError (undefined method `encoding' on nil:NilClass.):
  kernel/delta/kernel.rb:78:in `encoding (method_missing)'
  rubysl-cgi (2.0.0) lib/cgi/util.rb:7:in `escape'
  oauth (0.4.7) lib/oauth/tokens/request_token.rb:28:in `build_authorize_url'
  kernel/common/enumerable.rb:49:in `collect'
  kernel/common/hash.rb:342:in `each'
  kernel/common/enumerable.rb:48:in `map (collect)'
  oauth (0.4.7) lib/oauth/tokens/request_token.rb:28:in `build_authorize_url'
  oauth (0.4.7) lib/oauth/tokens/request_token.rb:9:in `authorize_url'
  omniauth-oauth (1.0.1) lib/omniauth/strategies/oauth.rb:36:in `old_request_phase (request_phase)'
  omniauth-twitter (1.0.0) lib/omniauth/strategies/twitter.rb:63:in `request_phase'
  omniauth (1.1.4) lib/omniauth/strategy.rb:214:in `request_call'
  omniauth (1.1.4) lib/omniauth/strategy.rb:181:in `call!'
  omniauth (1.1.4) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.1.4) lib/omniauth/builder.rb:49:in `call'
  mongoid (3.1.4) lib/rack/mongoid/middleware/identity_map.rb:34:in `call'
  mongoid (3.1.4) lib/mongoid/unit_of_work.rb:39:in `unit_of_work'
  mongoid (3.1.4) lib/rack/mongoid/middleware/identity_map.rb:34:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `call'
  kernel/bootstrap/proc.rb:20:in `call'
  kernel/common/throw_catch.rb:30:in `catch'
  kernel/common/throw_catch.rb:7:in `register'
  kernel/common/throw_catch.rb:29:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
  activesupport (3.2.14) lib/active_support/callbacks.rb:405:in `_run__1407416434714871310__call__1338411874204908663__callbacks'
  activesupport (3.2.14) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.14) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.14) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.14) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.14) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.14) lib/rails/rack/logger.rb:18:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.14) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.14) lib/rails/engine.rb:484:in `call'
  railties (3.2.14) lib/rails/application.rb:231:in `call'
  railties (3.2.14) lib/rails/railtie/configurable.rb:30:in `call (method_missing)'
  puma (2.6.0) lib/puma/configuration.rb:68:in `call'
  puma (2.6.0) lib/puma/server.rb:486:in `handle_request'
  puma (2.6.0) lib/puma/server.rb:357:in `process_client'
  puma (2.6.0) lib/puma/server.rb:250:in `run'
  kernel/bootstrap/proc.rb:20:in `call'
  puma (2.6.0) lib/puma/thread_pool.rb:92:in `spawn_thread'
  kernel/bootstrap/proc.rb:20:in `call'
  kernel/bootstrap/thread.rb:390:in `__run__'
```

**Comment by YorickPeterse** [comment] 2015-02-18 19:02
@kevinzhow Have you had any time to dig into this since first reporting and/or continued to experience the problem using newer versions of Rubinius?

**Comment by YorickPeterse** [comment] 2015-07-30 21:57
Closing this due to the lack of further feedback and the repository that supposedly reproduces this problem no longer existing. Feel free to re-open if the issue still persists when using the latest version of Rubinius.

**Closed by YorickPeterse** 2015-07-30 21:57 UTC
Labels: Needs feedback
