### ISSUE TITLE
RPI suppport

### ISSUE THREAD

**Issue by grandafrato** [rubinius/rubinius#3698] opened 2016-09-22 02:58 UTC
Please add raspberry pi (which is a computer) support by letting it be compiled using gcc instead of clang because raspbian (the OS) dosen't support llvm or clang.

**Comment by brixen** [comment] 2016-09-22 05:04
@LTheGreats hi! I'd love to support Raspberry Pi. Could you point me to where raspbian docs why it doesn't support llvm or clang? A bunch of years ago I compiled clang + Rubinius on a Beagle Bone, so I'm pretty sure it's not a hardware thing. At the least, I'd be happy to figure out how we can provide a binary for Raspberry Pi 3 (which is 64-bit).

**Comment by LTheGreats** [comment] 2016-09-23 00:05
I'm sorry forgot that I could get the source code compile it. But I think it would be a good idea to make binary so that people could get it using apt-get.

**Comment by brixen** [comment] 2016-09-23 00:41
@LTheGreats do you know offhand if vanilla debian packages work with raspbian? We have basic debian packaging in the Rubinius source, but I haven't updated it in quite a while.

**Comment by LTheGreats** [comment] 2016-09-23 00:45
I think so.

**Comment by LTheGreats** [comment] 2016-09-23 02:09
@brixen  I  learned that cdbs libncursesw5-dev, libreadline6-dev, libssl-dev, quilt, bison and libyaml-dev binarys do not exist for the raspberry pi.

**Comment by brixen** [comment] 2016-09-23 16:49
@LTheGreats ah, ok. So this may take a little work to get going. Have you looked into cross-compiling a binary for raspian? That way, we can build it on a regular computer and building all those libraries will go much faster.

If you've already looked into it, but need help getting started, let me know. If you haven't experimented with cross-compiling yet, it can be pretty tricky sometimes. I'm happy to look into it.

**Comment by LTheGreats** [comment] 2016-09-23 21:11
I don't have a cumputer that has a arm processor except the raspberry pi.

**Comment by brixen** [comment] 2016-09-23 22:10
@LTheGreats the cool thing about cross-compiling is that it's often possible to do so on a different architecture. That way, you can bootstrap hardware where your application isn't running yet, for example.

I'll see what I can find out about doing this for the Raspberry Pi. Which version do you have?

**Comment by burningTyger** [comment] 2016-09-24 08:16
Arch for Arm supports clang if that matters. But speed and memory was an obstacle in running rubinius last time I tried.

**Comment by LTheGreats** [comment] 2016-09-25 04:21
@brixen sorry for replying late. I have a raspberry pi 3 B.

**Comment by medols** [comment] 2016-10-16 19:48
@LTheGreats, @brixen, @burningTyger,  follows some rubinius build info on Raspberry Pi 3.

Install Rasbian using NOOB LITE:

https://www.raspberrypi.org/downloads/noobs/

Upgrade the installed debian jessie (stable) to debian stretch (testing):

https://www.debian.org/releases/stretch/i386/release-notes/ch-upgrading.en.html

Using this repository:

echo "deb http://mirrors.mit.edu/raspbian/raspbian/ stretch main contrib non-free rpi" > /etc/apt/sources.list

After debian stretch is ready run uname -a:

Linux raspberrypi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux

Install additional packages:

apt-get install libsodium-dev lldb

Download rubinius-3.46 sources:

wget https://github.com/rubinius/rubinius/releases/download/v3.46/rubinius-3.46.tar.bz2

Replace configure:458 with:

feature "vendor-libsodium", false

Replace machine/util/atomic.hpp:70 with:

__sync_synchronize();

Add this depencency to link machine/vm with clang++:

/usr/lib/arm-linux-gnueabihf/libsodium.a

Configure with:

./configure --debug-build --prefix=/home/pi/rubinius/rbx-3.46 --llvm-config=llvm-config-3.6

Build with:

bundle exec rake build --trace

Then get:

https://gist.github.com/medols/02fe9848ff42512e0967537485c50d2a

Finally try to debug with lldb:

pi@raspberrypi:~/rubinius/rubinius-3.46/staging/runtime/gems/rubinius-melbourne-3.7/ext/rubinius/code/melbourne $ lldb -f /home/pi/rubinius/rubinius-3.46/staging/bin/rbx -- -v
(lldb) target create "/home/pi/rubinius/rubinius-3.46/staging/bin/rbx"
Current executable set to '/home/pi/rubinius/rubinius-3.46/staging/bin/rbx' (arm).
(lldb) settings set -- target.run-args  "-v"
(lldb) r
Process 19706 launching
Process 19706 launched: '/home/pi/rubinius/rubinius-3.46/staging/bin/rbx' (arm)
Segmentation fault
pi@raspberrypi:~/rubinius/rubinius-3.46/staging/runtime/gems/rubinius-melbourne-3.7/ext/rubinius/code/melbourne $

**Comment by brixen** [comment] 2016-10-16 21:30
@medols wow, awesome work, thank you! I'm going to order an RPi3 so I can help out with this but I won't be back in the U.S. until late November, so it'll have to wait till then. In the meantime, I'm happy to take PRs to address some of the code issues with proper `#ifdef`s or whatever you think is needed. Feel free to open a WIP pull request. ❤️ 👍

**Comment by brixen** [comment] 2016-10-17 03:29
@medols if you have time, could you run under lldb like this:

```
$ lldb -f /home/pi/rubinius/rubinius-3.46/staging/bin/rbx -- -v
(lldb) br set -n main
(lldb) r
(lldb) n
```

Then keep hitting `n` at the lldb prompt until you get a segfault. If you want to dig deeper, try using `s` (step into) at the point where you got the segfault (you'll have to start the run over and use `n` to get back to just before that point).

Alternatively, you can step into (with `s`) as you go the first time, and if you are too deep, use `finish` to continue running until the function you are in is done.

**Comment by medols** [comment] 2016-10-17 06:14
@brixen the output is almost the same

$ lldb -f /home/pi/rubinius/rubinius-3.46/staging/bin/rbx -- -v
(lldb) target create "/home/pi/rubinius/rubinius-3.46/staging/bin/rbx"
Current executable set to '/home/pi/rubinius/rubinius-3.46/staging/bin/rbx' (arm).
(lldb) settings set -- target.run-args  "-v"
(lldb) br set -n main
Breakpoint 1: where = rbx`main + 40 at cli.cpp:35, address = 0x0033563c
(lldb) r
Process 21224 launching
Process 21224 launched: '/home/pi/rubinius/rubinius-3.46/staging/bin/rbx' (arm)
Segmentation fault

**Comment by medols** [comment] 2016-10-17 10:30
@brixen thank you for your feedback :-)

shall I PRs to 3.46? RPi3 flags are set to boot as 32bit arm7

got additionl info with gdb

https://gist.github.com/medols/59c55da71cc460125ad3548c86347073

**Comment by brixen** [comment] 2016-10-17 20:35
@medols ah, this line from your lldb session looks very curious,

```
Breakpoint 1, main (argc=<error reading variable: Cannot access memory at address 0xfffffff0>, argv=<error reading variable: Cannot access memory at address 0xffffffec>)
    at machine/drivers/cli.cpp:34
```

It looks like there's a problem with the executable, which could be caused by LLVM or the OS or ... something.

Your question about 32bit is very important. I want to do two things: 1. inventory the areas in Rubinius where I think 64bit support is critical; and 2. look into making a 64bit OS image for RPi3. This will take me a little time.

I know that just supporting 32bit would be a simple way to make it work on stuff like the RPi, but there are also things I want Rubinius to be able to do that are really hard to support on both 32bit and 64bit.

**Comment by medols** [comment] 2016-10-19 08:46
@brixen lldb-3.6 seems broken in rpi:

pi@raspberrypi:~/rubinius/tmp $ cat t.c 
int main (int argc, char *argv[]){ return 0; }
pi@raspberrypi:~/rubinius/tmp $ clang-3.6 -g t.c -o t
pi@raspberrypi:~/rubinius/tmp $ lldb-3.6 t
(lldb) target create "t"
Current executable set to 't' (arm).
(lldb) br set -n main
Breakpoint 1: where = t`main + 20 at t.c:3, address = 0x00010420
(lldb) r
Process 18095 launching
Process 18095 launched: '/home/pi/rubinius/tmp/t' (arm)
Segmentation fault
pi@raspberrypi:~/rubinius/tmp $ 

We have looked for a 64bit RPi image without much success.

If any is available we can try it.

**Comment by brixen** [comment] 2016-10-19 19:39
@medols from what I understand, there is not a 64bit image available, so we'd need to create one.

**Comment by medols** [comment] 2016-10-21 13:57
@brixen installing ubuntu 16.04 for RPi3

https://wiki.ubuntu.com/ARM/RaspberryPi#Download

then adding

https://wiki.ubuntu.com/ARM/RaspberryPi/RaspberryPi3#A64-bit_kernel.2Fuserland

gets an aarch64 linux kernel up and running:

ubuntu@ubuntu:~$ cat /proc/version 
Linux version 4.5.0+ (nao@ubuntu) (gcc version 4.8.2 20140110 (prerelease) [ibm/gcc-4_8-branch merged from gcc-4_8-branch, revision 205847] (Ubuntu/Linaro 4.8.2-13ubuntu1) ) #1 SMP PREEMPT Tue Apr 12 22:51:39 PDT 2016
ubuntu@ubuntu:~$ lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
ubuntu@ubuntu:~$ 

Nevertheless, precompiled llvm binaries for aarch64 are not recognized.

Moreover, all the available ubuntu packages are 32 bit.

Seems that some kind of crosscompiling is required, suggestions are welcome.

**Comment by medols** [comment] 2016-10-21 16:08
To get arm64 packages working:

[sudo] dpkg --add-architecture arm64
[sudo] apt-get install clang-3.6:arm64

**Comment by brixen** [comment] 2016-10-22 05:05
@medols this is so cool! I'm really sorry I cannot help right now but I'm so stoked that you're making progress on this. Hope you can keep working on it. ❤️ 👍

**Comment by LTheGreats** [comment] 2016-10-22 18:02
I reimaged my raspberry pi whith ubuntu which has the clang librarys installed on it!`

**Comment by LTheGreats** [comment] 2016-10-22 19:32
When I started configuring rubinius on the raspberry pi 3 (which is 64bit) I got this error message:

Support for non-64bit platforms was deprecated 1 Jun 2016 and has now been removed. If non-64bit support is a critical feature for your application, please email contact@rubinius.com

Running 'configure' failed. Please check configure.log for more details.

**Comment by medols** [comment] 2016-10-24 18:20
@LTheGreats, @brixen the complete dependency list for U

buntu with an aarch64 kernel is:

[sudo] dpkg --add-architecture arm64
[sudo] apt-get install clang-3.6:arm64
[sudo] apt-get install g++:arm64
[sudo] apt-get install ruby2.3-dev:arm64
[sudo] ln -s /usr/bin/ruby2.3 /usr/bin/ruby
[sudo] ln -s /usr/bin/gem2.3 /usr/bin/gem
[sudo] apt-get install zlib1g-dev:arm64
[sudo] apt-get install libssl-dev:arm64
[sudo] apt-get install libedit-dev:arm64
[sudo] apt-get install libncursesw5-dev:arm64

Using PR https://github.com/rubinius/rubinius/pull/3705 compile with:

./configure --prefix=/destination/path/rbx-3.62 --llvm-config=/usr/lib/llvm-3.6/bin/llvm-config --cc=/usr/lib/llvm-3.6/bin/clang --cxx=/usr/lib/llvm-3.6/bin/clang++

**Comment by medols** [comment] 2016-10-24 18:36
Find the binaries here:

[rbx-3.62_part1.zip](https://github.com/rubinius/rubinius/files/548665/rbx-3.62_part1.zip)
[rbx-3.62_part2.zip](https://github.com/rubinius/rubinius/files/548667/rbx-3.62_part2.zip)

ubuntu@ubuntu:~$ ruby -v
rubinius 3.62 (2.3.1 65e96fba 2016-10-14 3.6.2) [aarch64-linux-gnu]

**Comment by LTheGreats** [comment] 2016-11-03 00:04
Thanks!

**Comment by LTheGreats** [comment] 2016-11-08 04:01
The binary didn't work because of some executable error.

**Comment by brixen** [comment] 2016-11-08 04:25
@LTheGreats could you gist the error?

**Comment by LTheGreats** [comment] 2016-11-10 00:38
Here is the gist for the error:
{% gist 0f3ac0dea019fbc5dc283a82743c5c52 %}

**Comment by medols** [comment] 2016-11-10 06:52
@LTheGreats can you check this?

ubuntu@ubuntu:~/rbx-3.62$ file ./bin/rbx 
./bin/rbx: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped
ubuntu@ubuntu:~/rbx-3.62$ md5sum ./bin/rbx 
589a7af86c5e5c1d0786111b046f5e43  ./bin/rbx
ubuntu@ubuntu:~/rbx-3.62$ ldd ./bin/rbx 
	not a dynamic executable
ubuntu@ubuntu:~/rbx-3.62$ uname -a
Linux ubuntu 4.5.0+ #1 SMP PREEMPT Tue Apr 12 22:51:39 PDT 2016 aarch64 aarch64 aarch64 GNU/Linux

**Comment by LTheGreats** [comment] 2016-11-10 15:32
I checked and I found out why I got the error and it was because that it is compiled for aarch64 but when I ran uname -a it returned:
 Linux razpi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux

**Comment by medols** [comment] 2016-11-10 15:47
@LTheGreats , just change to aarch64:

ubuntu@ubuntu:~$ wget http://www.finnie.org/software/raspberrypi/ubuntu-rpi3/20160517-raspi3-arm64-firmware-kernel.tar.xz
--2016-11-10 15:43:11--  http://www.finnie.org/software/raspberrypi/ubuntu-rpi3/20160517-raspi3-arm64-firmware-kernel.tar.xz
Resolving www.finnie.org (www.finnie.org)... 209.177.154.210, 2001:470:67:107::2
Connecting to www.finnie.org (www.finnie.org)|209.177.154.210|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20332880 (19M) [application/x-tar]
Saving to: ‘20160517-raspi3-arm64-firmware-kernel.tar.xz’

20160517-raspi3-arm64-firmware-kernel.tar.xz  100%[============================================>]  19.39M  1.86MB/s    in 11s     

2016-11-10 15:43:24 (1.83 MB/s) - ‘20160517-raspi3-arm64-firmware-kernel.tar.xz’ saved [20332880/20332880]

ubuntu@ubuntu:~$ sudo su
root@ubuntu:/home/ubuntu# cd /
root@ubuntu:/# tar xvfJ /home/ubuntu/20160517-raspi3-arm64-firmware-kernel.tar.xz

**Comment by LTheGreats** [comment] 2016-11-11 01:43
I ran what you said above and it didn't work. I think it might be because Raspbian  does not support AArch64.

**Comment by medols** [comment] 2016-11-11 07:42
@LTheGreats the change to aarch64 works with this ubuntu 16.04 image for RPi3:

https://wiki.ubuntu.com/ARM/RaspberryPi#Download

It should work with the image you installed adding dependencies listed above:

https://github.com/rubinius/rubinius/issues/3698#issuecomment-255543927

**Comment by LTheGreats** [comment] 2016-11-11 14:13
Okay I will try to use that ubuntu image,

**Comment by LTheGreats** [comment] 2016-11-11 14:18
I also found out why the chang to AArch64 didn't work and that was because the Raspbian image is made to wark with the older 32bit RPIs

**Comment by medols** [comment] 2019-05-30 06:50
It seems that Ubuntu images with 64-ARM kernel will be officially released from now on:

"Raspberry Pi 3 (64-bit ARM) preinstalled server image. For Raspberry Pi 3 boards."

http://cdimage.ubuntu.com/releases/18.04.2/release/

Rubinius 4.0 runs on RPi3-64bit with a small patch to avoid minor vm:test issues

https://github.com/medols/rubinius/commit/795c78501c706f37a660f1e60f1c087644fdb63b

Travis-ci is also able to build a release

https://travis-ci.org/medols/rubinius-pi-docker/builds/538933684

The timeout is due to the qemu-aarch64-static overhead but it completes when run locally.

I am looking for ways to increase the build granularity and split the process into several stages.

For example, stop travis-ci when the "rakelib/blueprint.rb" finishes with "files << oniguruma".

```
1886   1: CC enc/trans/utf_16_32.c
1887   1: LDSHARED enc/trans/utf_16_32.so
```

Let's see if releases can be automated :-)

**Comment by brixen** [comment] 2020-01-05 00:27
In general, Rubinius enthusiastically supports experimentation and welcomes ideas for features that enhance developer ability to create amazing software.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to support more efforts around experimentation.

**Closed by brixen** 2020-01-05 00:27 UTC
Labels: OS & Platform
