### ISSUE TITLE
Rubinius crashes when closing a Gosu window

### ISSUE THREAD

**Issue by anthropomorphic** [rubinius/rubinius#2865] opened 2014-01-01 21:26 UTC
[here](https://gist.github.com/anonymous/d340c7b4ecdfd84a2734) is a crash report, and [here](https://github.com/jlnr/gosu) is the source for Gosu.

**Comment by YorickPeterse** [comment] 2015-01-01 18:23
Can't reproduce this using the following snippet:

```ruby
require 'gosu'

window = Gosu::Window.new(100, 100, false)
window.caption = 'Rubinius 2865'
window.show
```

Closing it as a result, feel free to re-open if the issue still persists. If doing so, please provide more information such as the full GDB backtrace (`gdb --args rbx ruby_file.rb` followed by `thread apply all bt` in the console), LLVM version, etc.

**Closed by YorickPeterse** 2015-01-01 18:23 UTC
Labels: crash
