### ISSUE TITLE
Rubinius crash

### ISSUE THREAD

**Issue by neoecos** [rubinius/rubinius#3091] opened 2014-07-18 17:06 UTC
Hi, using rbx 2.2.10 with rails 3.2.19 with config.threadsafe! this started to happend

https://gist.github.com/fd92b9fd20315e5111fd

**Comment by YorickPeterse** [comment] 2015-01-01 18:38
@neoecos Any news, can you provide a way to reproduce this?

**Comment by YorickPeterse** [comment] 2015-07-30 22:02
Closing this due to lack of further feedback. Feel free to re-open if the issue still persists when using the latest version of Rubinius.

**Closed by YorickPeterse** 2015-07-30 22:02 UTC
Labels: crash, Needs feedback
